CREATE TABLE ARTIST(
    ID BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL UNIQUE,
    YEAR INT,
);

CREATE TABLE MUSIC(
    ID BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    ARTIST_ID BIGINT NOT NULL,
);

ALTER TABLE MUSIC ADD FOREIGN KEY(ARTIST_ID) REFERENCES ARTIST(ID);
