CREATE TABLE ARTIST(
    ID BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL UNIQUE,
);
CREATE TABLE MUSIC(
    ID BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    ARTIST_ID BIGINT NOT NULL,
);
ALTER TABLE MUSIC ADD FOREIGN KEY(ARTIST_ID) REFERENCES JOB(ARTIST);