INSERT INTO ARTIST(ID, NAME, YEAR) VALUES (1, 'Iron Maiden', 1975);
INSERT INTO ARTIST(ID, NAME, YEAR) VALUES (2, 'Metallica', 1981);
INSERT INTO ARTIST(ID, NAME, YEAR) VALUES (3, 'Black Sabbath', 1968);

INSERT INTO MUSIC(ID, NAME, ARTIST_ID) VALUES (1, 'Aces High', 1);
INSERT INTO MUSIC(ID, NAME, ARTIST_ID) VALUES (2, 'Wrathchild', 1);
INSERT INTO MUSIC(ID, NAME, ARTIST_ID) VALUES (3, 'Fear of the Dark', 1);

INSERT INTO MUSIC(ID, NAME, ARTIST_ID) VALUES (4, 'Battery', 2);
INSERT INTO MUSIC(ID, NAME, ARTIST_ID) VALUES (5, 'Enter Sandman', 2);
INSERT INTO MUSIC(ID, NAME, ARTIST_ID) VALUES (6, 'Sad But True', 2);

INSERT INTO MUSIC(ID, NAME, ARTIST_ID) VALUES (7, 'Paranoid', 3);
INSERT INTO MUSIC(ID, NAME, ARTIST_ID) VALUES (8, 'Iron Man', 3);
INSERT INTO MUSIC(ID, NAME, ARTIST_ID) VALUES (9, 'War Pigs', 3);